vich_uploader:
    db_driver: orm

    mappings:
        vehicule:
            uri_prefix: /IMG/vehicule
            upload_destination: '%kernel.project_dir%/public/IMG/vehicule'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
